version: '2'

services:
    nginx:
        build: .
        volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./index.html:/var/www/index.html
        ports:
        - 80:80
        restart: always